# Description: This file contains all the constants used in the project
X_POSITION_COLUMN_NAME='x'
Y_POSITION_COLUMN_NAME='y'
TIME_COLUMN_NAME='t'
FRAME_COLUMN_NAME='frame'
CLUSTER_ID_COLUMN_NAME='cluster_id'
CLUSTERIZED_COLUMN_NAME='clusterized'
PARTICLE_ID_COLUMN_NAME='particle_id'

MAGIK_POSITION_COLUMN_NAME = 'position'
MAGIK_X_POSITION_COLUMN_NAME=f'{MAGIK_POSITION_COLUMN_NAME}-x'
MAGIK_Y_POSITION_COLUMN_NAME=f'{MAGIK_POSITION_COLUMN_NAME}-y'
MAGIK_LABEL_COLUMN_NAME='solution'
MAGIK_DATASET_COLUMN_NAME='set'
MAGIK_LABEL_COLUMN_NAME_PREDICTED=MAGIK_LABEL_COLUMN_NAME+"_predicted"
